# Build stage
FROM node:24.8.0-alpine

ENV NODE_ENV=production
ENV HOST=0.0.0.0
ENV PORT=3000

EXPOSE 3000

RUN corepack enable

WORKDIR /app

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml nx.json tsconfig.json tsconfig.base.json ./
COPY apps/indexer ./apps/indexer
COPY packages ./packages
COPY tmp ./tmp

RUN pnpm install

RUN pnpm nx build indexer

CMD [ "node", "apps/indexer/dist/main.js" ]
