FROM node:24.8.0-alpine AS base

RUN corepack enable
RUN corepack prepare pnpm@latest-10 --activate

WORKDIR /app

COPY package.json ./

# Install deps
RUN pnpm install

FROM base AS build

COPY . ./

# Build the app
RUN pnpm nx build indexer

FROM node:24.8.0-alpine AS production

RUN corepack enable
RUN corepack prepare pnpm@latest-10 --activate

WORKDIR /app

COPY package.json ./
# Install only production deps
RUN pnpm install --production
# Copy built files from the build stage
COPY --from=build /app/apps/indexer/dist ./indexer

# Set environment variables
ENV NODE_ENV=production
ENV PORT=8000

EXPOSE 8000

ENTRYPOINT [ "node", "indexer/main.js" ]
