name: Build Indexer

on:
  push:
    branches: [develop, staging, main]
    paths:
      - 'apps/indexer/*'
  workflow_dispatch:

jobs:
  call-workflow-init:
    uses: DistributedCollective/.github/.github/workflows/init.yml@v2_staging
    with:
      ref: ${{ github.ref }}
      base_ref: ${{ github.base_ref }}

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        node-version: [24.x]

    steps:
      - uses: actions/checkout@v4
      - name: PNPM cache
        id: cache-pnpm
        uses: actions/cache@v4
        env:
          cache-name: cache-pnpm
        with:
          path: |
            node_modules
            ~/.pnpm
          key: ${{ runner.os }}-test-${{ env.cache-name }}-pnpm-${{ hashFiles('**/package-lock.json') }}

      - name: NX cache
        id: cache-nx
        uses: actions/cache@v4
        env:
          cache-name: cache-nx
        with:
          path: |
            .nx
          key: ${{ runner.os }}-test-${{ env.cache-name }}-nx-${{ hashFiles('**/package-lock.json') }}

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: false

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install Dependencies
        if: steps.cache-pnpm.outputs.cache-hit != 'true'
        run: pnpm install

      - name: Build indexer
        run: pnpm nx build indexer

        # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Login to registry ${{ needs.call-workflow-init.outputs.registry }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3.0.0
        with:
          registry: ${{ needs.call-workflow-init.outputs.registry }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5.0.0
        with:
          images: ${{ needs.call-workflow-init.outputs.registry }}/${{ needs.call-workflow-init.outputs.image_name }}

      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image
        uses: docker/build-push-action@v5.0.0
        with:
          context: .
          file: ${{ needs.call-workflow-init.outputs.dockerfile_path }}/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ needs.call-workflow-init.outputs.registry }}/${{ inputs.IMAGE_NAME }}:${{ inputs.KUBE_NAMESPACE }}
          labels: ${{ steps.meta.outputs.labels }}
