name: Run Tests

on:
  push:
    branches: ['develop', 'main']
  pull_request:
    branches: ['develop', 'main']

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [24.x]

    steps:
      - uses: actions/checkout@v4

      - name: PNPM cache
        id: cache-pnpm
        uses: actions/cache@v4
        env:
          cache-name: cache-pnpm
        with:
          path: |
            node_modules
            ~/.pnpm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-pnpm-${{ hashFiles('**/package-lock.json') }}

      - name: NX cache
        id: cache-nx
        uses: actions/cache@v4
        env:
          cache-name: cache-nx
        with:
          path: |
            .nx
          key: ${{ runner.os }}-build-${{ env.cache-name }}-nx-${{ hashFiles('**/package-lock.json') }}

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: false

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install Dependencies
        if: steps.cache-pnpm.outputs.cache-hit != 'true'
        run: pnpm install

      - name: Run Tests
        run: pnpm nx run-many -t test
